//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 11:05:34 AM ICT 
//


package bidv.soa.sibs.acctUnHold;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctUnholdReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctUnholdReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/global/vn/account/accthold/unhold/1.0}BodyReqAcctUnhold"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "AcctUnholdReq", namespace = "http://www.bidv.com/global/vn/account/accthold/unhold/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctUnholdReqType", namespace = "http://www.bidv.com/global/vn/account/accthold/unhold/1.0", propOrder = {
    "bodyReqAcctUnhold"
})
public class AcctUnholdReqType
    extends BaseServiceEnvelopeRequestType
{

    @XmlElement(name = "BodyReqAcctUnhold", required = true)
    protected BodyReqAcctUnholdType bodyReqAcctUnhold;

    /**
     * Gets the value of the bodyReqAcctUnhold property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqAcctUnholdType }
     *     
     */
    public BodyReqAcctUnholdType getBodyReqAcctUnhold() {
        return bodyReqAcctUnhold;
    }

    /**
     * Sets the value of the bodyReqAcctUnhold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqAcctUnholdType }
     *     
     */
    public void setBodyReqAcctUnhold(BodyReqAcctUnholdType value) {
        this.bodyReqAcctUnhold = value;
    }

}
