//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.07 at 02:05:49 PM ICT 
//


package bidv.soa.sibs.acctList.listAcct;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListAccResType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListAccResType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeResponseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com.vn/entity/global/vn/account/acctlist/listacc/1.0}BodyResInquiry"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "ListAccRes", namespace = "http://www.bidv.com.vn/entity/global/vn/account/acctlist/listacc/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListAccResType", namespace = "http://www.bidv.com.vn/entity/global/vn/account/acctlist/listacc/1.0", propOrder = {
    "bodyResInquiry"
})
public class ListAccResType
    extends BaseServiceEnvelopeResponseType
{

    @XmlElement(name = "BodyResInquiry", required = true)
    protected BodyResInquiryType bodyResInquiry;

    /**
     * Gets the value of the bodyResInquiry property.
     * 
     * @return
     *     possible object is
     *     {@link BodyResInquiryType }
     *     
     */
    public BodyResInquiryType getBodyResInquiry() {
        return bodyResInquiry;
    }

    /**
     * Sets the value of the bodyResInquiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyResInquiryType }
     *     
     */
    public void setBodyResInquiry(BodyResInquiryType value) {
        this.bodyResInquiry = value;
    }

}
