//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.07 at 02:05:49 PM ICT 
//


package bidv.soa.sibs.acctList.listAcct;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RepeatedFieldsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RepeatedFieldsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccInfoType" type="{http://www.bidv.com/global/common/account/1.0}AcctInfoType" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OriginalBalance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccRelation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LedgerBalance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerName1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccountTypeDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SerialNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaturityDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Channel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JoinAcct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Minblm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrdCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MoreInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RepeatedFieldsType", namespace = "http://www.bidv.com.vn/entity/global/vn/account/acctlist/listacc/1.0", propOrder = {
    "accInfoType",
    "currency",
    "originalBalance",
    "accRelation",
    "ledgerBalance",
    "customerName1",
    "accountTypeDesc",
    "accStatus",
    "branchCode",
    "serialNo",
    "maturityDt",
    "channel",
    "joinAcct",
    "minblm",
    "prdCode",
    "moreInfo"
})
public class RepeatedFieldsType {

    @XmlElement(name = "AccInfoType")
    protected AcctInfoType accInfoType;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "OriginalBalance")
    protected String originalBalance;
    @XmlElement(name = "AccRelation")
    protected String accRelation;
    @XmlElement(name = "LedgerBalance")
    protected String ledgerBalance;
    @XmlElement(name = "CustomerName1")
    protected String customerName1;
    @XmlElement(name = "AccountTypeDesc")
    protected String accountTypeDesc;
    @XmlElement(name = "AccStatus")
    protected String accStatus;
    @XmlElement(name = "BranchCode")
    protected String branchCode;
    @XmlElement(name = "SerialNo")
    protected String serialNo;
    @XmlElement(name = "MaturityDt")
    protected String maturityDt;
    @XmlElement(name = "Channel")
    protected String channel;
    @XmlElement(name = "JoinAcct")
    protected String joinAcct;
    @XmlElement(name = "Minblm")
    protected String minblm;
    @XmlElement(name = "PrdCode")
    protected String prdCode;
    @XmlElement(name = "MoreInfo")
    protected String moreInfo;

    /**
     * Gets the value of the accInfoType property.
     * 
     * @return
     *     possible object is
     *     {@link AcctInfoType }
     *     
     */
    public AcctInfoType getAccInfoType() {
        return accInfoType;
    }

    /**
     * Sets the value of the accInfoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcctInfoType }
     *     
     */
    public void setAccInfoType(AcctInfoType value) {
        this.accInfoType = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the originalBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalBalance() {
        return originalBalance;
    }

    /**
     * Sets the value of the originalBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalBalance(String value) {
        this.originalBalance = value;
    }

    /**
     * Gets the value of the accRelation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccRelation() {
        return accRelation;
    }

    /**
     * Sets the value of the accRelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccRelation(String value) {
        this.accRelation = value;
    }

    /**
     * Gets the value of the ledgerBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLedgerBalance() {
        return ledgerBalance;
    }

    /**
     * Sets the value of the ledgerBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLedgerBalance(String value) {
        this.ledgerBalance = value;
    }

    /**
     * Gets the value of the customerName1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName1() {
        return customerName1;
    }

    /**
     * Sets the value of the customerName1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName1(String value) {
        this.customerName1 = value;
    }

    /**
     * Gets the value of the accountTypeDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountTypeDesc() {
        return accountTypeDesc;
    }

    /**
     * Sets the value of the accountTypeDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountTypeDesc(String value) {
        this.accountTypeDesc = value;
    }

    /**
     * Gets the value of the accStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccStatus() {
        return accStatus;
    }

    /**
     * Sets the value of the accStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccStatus(String value) {
        this.accStatus = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCode(String value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the serialNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * Sets the value of the serialNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNo(String value) {
        this.serialNo = value;
    }

    /**
     * Gets the value of the maturityDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityDt() {
        return maturityDt;
    }

    /**
     * Sets the value of the maturityDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityDt(String value) {
        this.maturityDt = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannel(String value) {
        this.channel = value;
    }

    /**
     * Gets the value of the joinAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinAcct() {
        return joinAcct;
    }

    /**
     * Sets the value of the joinAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinAcct(String value) {
        this.joinAcct = value;
    }

    /**
     * Gets the value of the minblm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinblm() {
        return minblm;
    }

    /**
     * Sets the value of the minblm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinblm(String value) {
        this.minblm = value;
    }

    /**
     * Gets the value of the prdCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrdCode() {
        return prdCode;
    }

    /**
     * Sets the value of the prdCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrdCode(String value) {
        this.prdCode = value;
    }

    /**
     * Gets the value of the moreInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoreInfo() {
        return moreInfo;
    }

    /**
     * Sets the value of the moreInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoreInfo(String value) {
        this.moreInfo = value;
    }

}
