//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.17 at 09:22:32 AM ICT 
//


package soa.apps.ecm.digitizationservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodyReqEcmDigitizationServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BodyReqEcmDigitizationServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="accessToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="appCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="checksum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="requestID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="relatedBranch" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transactionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentTypeId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createBySystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ecmUserCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ecmDateCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="approver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateApprove" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fileInput" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="customerType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="authorizationLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="authorizedPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="docDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="docEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="docNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="docValidityPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="documentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="expireDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="scopeOfAuthorized" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="signerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="serviceType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="docEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="docValidityPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="documentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cardType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cardType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="primaryCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="secondaryCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="staffNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="posUnitNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="captType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="tradeDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="valueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="typeOfDeal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="typeOfInstr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="foDealId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="paymentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="accountingID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="actionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="transferID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodyReqEcmDigitizationServiceType", namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0", propOrder = {
    "accessToken",
    "appCode",
    "checksum",
    "requestID",
    "branchCreated",
    "relatedBranch",
    "transactionId",
    "documentTypeId",
    "createBySystem",
    "ecmUserCreated",
    "ecmDateCreated",
    "approver",
    "dateApprove",
    "fileInput",
    "eType",
    "customerType",
    "serviceType",
    "cardType",
    "captType"
})
public class BodyReqEcmDigitizationServiceType {

    @XmlElement(required = true)
    protected String accessToken;
    @XmlElement(required = true)
    protected String appCode;
    @XmlElement(required = true)
    protected String checksum;
    @XmlElement(required = true)
    protected String requestID;
    protected String branchCreated;
    protected String relatedBranch;
    protected String transactionId;
    protected String documentTypeId;
    protected String createBySystem;
    protected String ecmUserCreated;
    protected String ecmDateCreated;
    protected String approver;
    protected String dateApprove;
    protected String fileInput;
    protected String eType;
    protected BodyReqEcmDigitizationServiceType.CustomerType customerType;
    protected BodyReqEcmDigitizationServiceType.ServiceType serviceType;
    protected BodyReqEcmDigitizationServiceType.CardType cardType;
    protected BodyReqEcmDigitizationServiceType.CaptType captType;

    /**
     * Gets the value of the accessToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Sets the value of the accessToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessToken(String value) {
        this.accessToken = value;
    }

    /**
     * Gets the value of the appCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppCode() {
        return appCode;
    }

    /**
     * Sets the value of the appCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppCode(String value) {
        this.appCode = value;
    }

    /**
     * Gets the value of the checksum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecksum() {
        return checksum;
    }

    /**
     * Sets the value of the checksum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecksum(String value) {
        this.checksum = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the branchCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchCreated() {
        return branchCreated;
    }

    /**
     * Sets the value of the branchCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchCreated(String value) {
        this.branchCreated = value;
    }

    /**
     * Gets the value of the relatedBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedBranch() {
        return relatedBranch;
    }

    /**
     * Sets the value of the relatedBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedBranch(String value) {
        this.relatedBranch = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the documentTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentTypeId() {
        return documentTypeId;
    }

    /**
     * Sets the value of the documentTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentTypeId(String value) {
        this.documentTypeId = value;
    }

    /**
     * Gets the value of the createBySystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateBySystem() {
        return createBySystem;
    }

    /**
     * Sets the value of the createBySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateBySystem(String value) {
        this.createBySystem = value;
    }

    /**
     * Gets the value of the ecmUserCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcmUserCreated() {
        return ecmUserCreated;
    }

    /**
     * Sets the value of the ecmUserCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcmUserCreated(String value) {
        this.ecmUserCreated = value;
    }

    /**
     * Gets the value of the ecmDateCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcmDateCreated() {
        return ecmDateCreated;
    }

    /**
     * Sets the value of the ecmDateCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcmDateCreated(String value) {
        this.ecmDateCreated = value;
    }

    /**
     * Gets the value of the approver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprover() {
        return approver;
    }

    /**
     * Sets the value of the approver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprover(String value) {
        this.approver = value;
    }

    /**
     * Gets the value of the dateApprove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateApprove() {
        return dateApprove;
    }

    /**
     * Sets the value of the dateApprove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateApprove(String value) {
        this.dateApprove = value;
    }

    /**
     * Gets the value of the fileInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileInput() {
        return fileInput;
    }

    /**
     * Sets the value of the fileInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileInput(String value) {
        this.fileInput = value;
    }

    /**
     * Gets the value of the eType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEType() {
        return eType;
    }

    /**
     * Sets the value of the eType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEType(String value) {
        this.eType = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqEcmDigitizationServiceType.CustomerType }
     *     
     */
    public BodyReqEcmDigitizationServiceType.CustomerType getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqEcmDigitizationServiceType.CustomerType }
     *     
     */
    public void setCustomerType(BodyReqEcmDigitizationServiceType.CustomerType value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqEcmDigitizationServiceType.ServiceType }
     *     
     */
    public BodyReqEcmDigitizationServiceType.ServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqEcmDigitizationServiceType.ServiceType }
     *     
     */
    public void setServiceType(BodyReqEcmDigitizationServiceType.ServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqEcmDigitizationServiceType.CardType }
     *     
     */
    public BodyReqEcmDigitizationServiceType.CardType getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqEcmDigitizationServiceType.CardType }
     *     
     */
    public void setCardType(BodyReqEcmDigitizationServiceType.CardType value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the captType property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqEcmDigitizationServiceType.CaptType }
     *     
     */
    public BodyReqEcmDigitizationServiceType.CaptType getCaptType() {
        return captType;
    }

    /**
     * Sets the value of the captType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqEcmDigitizationServiceType.CaptType }
     *     
     */
    public void setCaptType(BodyReqEcmDigitizationServiceType.CaptType value) {
        this.captType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="tradeDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="valueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="typeOfDeal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="typeOfInstr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="foDealId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="paymentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="accountingID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="actionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="transferID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cifNumber",
        "bdsCreated",
        "tradeDate",
        "valueDate",
        "typeOfDeal",
        "typeOfInstr",
        "foDealId",
        "paymentID",
        "accountingID",
        "currency",
        "endDate",
        "actionDate",
        "amount",
        "transferID"
    })
    public static class CaptType {

        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String cifNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String bdsCreated;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String tradeDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String valueDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String typeOfDeal;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String typeOfInstr;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String foDealId;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String paymentID;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String accountingID;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String currency;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String endDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String actionDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String amount;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String transferID;

        /**
         * Gets the value of the cifNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCifNumber() {
            return cifNumber;
        }

        /**
         * Sets the value of the cifNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCifNumber(String value) {
            this.cifNumber = value;
        }

        /**
         * Gets the value of the bdsCreated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBdsCreated() {
            return bdsCreated;
        }

        /**
         * Sets the value of the bdsCreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBdsCreated(String value) {
            this.bdsCreated = value;
        }

        /**
         * Gets the value of the tradeDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTradeDate() {
            return tradeDate;
        }

        /**
         * Sets the value of the tradeDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTradeDate(String value) {
            this.tradeDate = value;
        }

        /**
         * Gets the value of the valueDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValueDate() {
            return valueDate;
        }

        /**
         * Sets the value of the valueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValueDate(String value) {
            this.valueDate = value;
        }

        /**
         * Gets the value of the typeOfDeal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeOfDeal() {
            return typeOfDeal;
        }

        /**
         * Sets the value of the typeOfDeal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeOfDeal(String value) {
            this.typeOfDeal = value;
        }

        /**
         * Gets the value of the typeOfInstr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypeOfInstr() {
            return typeOfInstr;
        }

        /**
         * Sets the value of the typeOfInstr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypeOfInstr(String value) {
            this.typeOfInstr = value;
        }

        /**
         * Gets the value of the foDealId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFoDealId() {
            return foDealId;
        }

        /**
         * Sets the value of the foDealId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFoDealId(String value) {
            this.foDealId = value;
        }

        /**
         * Gets the value of the paymentID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentID() {
            return paymentID;
        }

        /**
         * Sets the value of the paymentID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentID(String value) {
            this.paymentID = value;
        }

        /**
         * Gets the value of the accountingID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccountingID() {
            return accountingID;
        }

        /**
         * Sets the value of the accountingID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccountingID(String value) {
            this.accountingID = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEndDate(String value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the actionDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActionDate() {
            return actionDate;
        }

        /**
         * Sets the value of the actionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionDate(String value) {
            this.actionDate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAmount(String value) {
            this.amount = value;
        }

        /**
         * Gets the value of the transferID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransferID() {
            return transferID;
        }

        /**
         * Sets the value of the transferID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransferID(String value) {
            this.transferID = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cardType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="primaryCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="secondaryCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="staffNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="posUnitNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cifNumber",
        "bdsCreated",
        "cardNumber",
        "productNumber",
        "cardType",
        "primaryCard",
        "secondaryCard",
        "staffNumber",
        "posUnitNumber",
        "expiryDate"
    })
    public static class CardType {

        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String cifNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String bdsCreated;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String cardNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String productNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String cardType;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String primaryCard;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String secondaryCard;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String staffNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String posUnitNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String expiryDate;

        /**
         * Gets the value of the cifNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCifNumber() {
            return cifNumber;
        }

        /**
         * Sets the value of the cifNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCifNumber(String value) {
            this.cifNumber = value;
        }

        /**
         * Gets the value of the bdsCreated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBdsCreated() {
            return bdsCreated;
        }

        /**
         * Sets the value of the bdsCreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBdsCreated(String value) {
            this.bdsCreated = value;
        }

        /**
         * Gets the value of the cardNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardNumber() {
            return cardNumber;
        }

        /**
         * Sets the value of the cardNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardNumber(String value) {
            this.cardNumber = value;
        }

        /**
         * Gets the value of the productNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductNumber() {
            return productNumber;
        }

        /**
         * Sets the value of the productNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductNumber(String value) {
            this.productNumber = value;
        }

        /**
         * Gets the value of the cardType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCardType() {
            return cardType;
        }

        /**
         * Sets the value of the cardType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCardType(String value) {
            this.cardType = value;
        }

        /**
         * Gets the value of the primaryCard property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimaryCard() {
            return primaryCard;
        }

        /**
         * Sets the value of the primaryCard property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimaryCard(String value) {
            this.primaryCard = value;
        }

        /**
         * Gets the value of the secondaryCard property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecondaryCard() {
            return secondaryCard;
        }

        /**
         * Sets the value of the secondaryCard property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecondaryCard(String value) {
            this.secondaryCard = value;
        }

        /**
         * Gets the value of the staffNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStaffNumber() {
            return staffNumber;
        }

        /**
         * Sets the value of the staffNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStaffNumber(String value) {
            this.staffNumber = value;
        }

        /**
         * Gets the value of the posUnitNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPosUnitNumber() {
            return posUnitNumber;
        }

        /**
         * Sets the value of the posUnitNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPosUnitNumber(String value) {
            this.posUnitNumber = value;
        }

        /**
         * Gets the value of the expiryDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpiryDate() {
            return expiryDate;
        }

        /**
         * Sets the value of the expiryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpiryDate(String value) {
            this.expiryDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="authorizationLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="authorizedPerson" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="docDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="docEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="docNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="docValidityPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="documentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="expireDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="scopeOfAuthorized" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="signerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cifNumber",
        "bdsCreated",
        "authorizationLimit",
        "authorizedPerson",
        "docDate",
        "docEffectiveDate",
        "docNumber",
        "docValidityPeriod",
        "documentStatus",
        "expireDate",
        "expiryDate",
        "scopeOfAuthorized",
        "signerName"
    })
    public static class CustomerType {

        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String cifNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String bdsCreated;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String authorizationLimit;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String authorizedPerson;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String docDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String docEffectiveDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String docNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String docValidityPeriod;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String documentStatus;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String expireDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String expiryDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String scopeOfAuthorized;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String signerName;

        /**
         * Gets the value of the cifNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCifNumber() {
            return cifNumber;
        }

        /**
         * Sets the value of the cifNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCifNumber(String value) {
            this.cifNumber = value;
        }

        /**
         * Gets the value of the bdsCreated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBdsCreated() {
            return bdsCreated;
        }

        /**
         * Sets the value of the bdsCreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBdsCreated(String value) {
            this.bdsCreated = value;
        }

        /**
         * Gets the value of the authorizationLimit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizationLimit() {
            return authorizationLimit;
        }

        /**
         * Sets the value of the authorizationLimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizationLimit(String value) {
            this.authorizationLimit = value;
        }

        /**
         * Gets the value of the authorizedPerson property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizedPerson() {
            return authorizedPerson;
        }

        /**
         * Sets the value of the authorizedPerson property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizedPerson(String value) {
            this.authorizedPerson = value;
        }

        /**
         * Gets the value of the docDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocDate() {
            return docDate;
        }

        /**
         * Sets the value of the docDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocDate(String value) {
            this.docDate = value;
        }

        /**
         * Gets the value of the docEffectiveDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocEffectiveDate() {
            return docEffectiveDate;
        }

        /**
         * Sets the value of the docEffectiveDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocEffectiveDate(String value) {
            this.docEffectiveDate = value;
        }

        /**
         * Gets the value of the docNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocNumber() {
            return docNumber;
        }

        /**
         * Sets the value of the docNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocNumber(String value) {
            this.docNumber = value;
        }

        /**
         * Gets the value of the docValidityPeriod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocValidityPeriod() {
            return docValidityPeriod;
        }

        /**
         * Sets the value of the docValidityPeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocValidityPeriod(String value) {
            this.docValidityPeriod = value;
        }

        /**
         * Gets the value of the documentStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentStatus() {
            return documentStatus;
        }

        /**
         * Sets the value of the documentStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentStatus(String value) {
            this.documentStatus = value;
        }

        /**
         * Gets the value of the expireDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpireDate() {
            return expireDate;
        }

        /**
         * Sets the value of the expireDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpireDate(String value) {
            this.expireDate = value;
        }

        /**
         * Gets the value of the expiryDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpiryDate() {
            return expiryDate;
        }

        /**
         * Sets the value of the expiryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpiryDate(String value) {
            this.expiryDate = value;
        }

        /**
         * Gets the value of the scopeOfAuthorized property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScopeOfAuthorized() {
            return scopeOfAuthorized;
        }

        /**
         * Sets the value of the scopeOfAuthorized property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScopeOfAuthorized(String value) {
            this.scopeOfAuthorized = value;
        }

        /**
         * Gets the value of the signerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSignerName() {
            return signerName;
        }

        /**
         * Sets the value of the signerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSignerName(String value) {
            this.signerName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="cifNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="bdsCreated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="docEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="docValidityPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="documentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cifNumber",
        "bdsCreated",
        "docEffectiveDate",
        "docValidityPeriod",
        "documentStatus",
        "expiryDate"
    })
    public static class ServiceType {

        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String cifNumber;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String bdsCreated;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String docEffectiveDate;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String docValidityPeriod;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String documentStatus;
        @XmlElement(namespace = "http://www.bidv.com/global/vn/apps/ecm/ecmdigitizationservice/1.0")
        protected String expiryDate;

        /**
         * Gets the value of the cifNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCifNumber() {
            return cifNumber;
        }

        /**
         * Sets the value of the cifNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCifNumber(String value) {
            this.cifNumber = value;
        }

        /**
         * Gets the value of the bdsCreated property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBdsCreated() {
            return bdsCreated;
        }

        /**
         * Sets the value of the bdsCreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBdsCreated(String value) {
            this.bdsCreated = value;
        }

        /**
         * Gets the value of the docEffectiveDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocEffectiveDate() {
            return docEffectiveDate;
        }

        /**
         * Sets the value of the docEffectiveDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocEffectiveDate(String value) {
            this.docEffectiveDate = value;
        }

        /**
         * Gets the value of the docValidityPeriod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocValidityPeriod() {
            return docValidityPeriod;
        }

        /**
         * Sets the value of the docValidityPeriod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocValidityPeriod(String value) {
            this.docValidityPeriod = value;
        }

        /**
         * Gets the value of the documentStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentStatus() {
            return documentStatus;
        }

        /**
         * Sets the value of the documentStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentStatus(String value) {
            this.documentStatus = value;
        }

        /**
         * Gets the value of the expiryDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpiryDate() {
            return expiryDate;
        }

        /**
         * Sets the value of the expiryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpiryDate(String value) {
            this.expiryDate = value;
        }

    }

}
