//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.18 at 09:36:10 AM ICT 
//


package soa.apps.email.sendmail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EMAILSendEmailResType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EMAILSendEmailResType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeResponseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/entity/vn/apps/email/sendemail/1.0}BodyResSendEmail"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "EMAILSendEmailRes", namespace = "http://www.bidv.com/entity/vn/apps/email/sendemail/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EMAILSendEmailResType", namespace = "http://www.bidv.com/entity/vn/apps/email/sendemail/1.0", propOrder = {
    "bodyResSendEmail"
})
public class EMAILSendEmailResType
    extends BaseServiceEnvelopeResponseType
{

    @XmlElement(name = "BodyResSendEmail", required = true)
    protected BodyResSendEmailType bodyResSendEmail;

    /**
     * Gets the value of the bodyResSendEmail property.
     * 
     * @return
     *     possible object is
     *     {@link BodyResSendEmailType }
     *     
     */
    public BodyResSendEmailType getBodyResSendEmail() {
        return bodyResSendEmail;
    }

    /**
     * Sets the value of the bodyResSendEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyResSendEmailType }
     *     
     */
    public void setBodyResSendEmail(BodyResSendEmailType value) {
        this.bodyResSendEmail = value;
    }

}
