//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 11:10:19 AM ICT 
//


package soa.apps.ecm.getListDocumentCrom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetListDocumentFromCROMReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetListDocumentFromCROMReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/global/vn/apps/ecm/getlistdocumentfromcrom/1.0}BodyReqGetListDocumentFromCROM"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "GetListDocumentFromCROMReq", namespace = "http://www.bidv.com/global/vn/apps/ecm/getlistdocumentfromcrom/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetListDocumentFromCROMReqType", namespace = "http://www.bidv.com/global/vn/apps/ecm/getlistdocumentfromcrom/1.0", propOrder = {
    "bodyReqGetListDocumentFromCROM"
})
public class GetListDocumentFromCROMReqType
    extends BaseServiceEnvelopeRequestType
{

    @XmlElement(name = "BodyReqGetListDocumentFromCROM", required = true)
    protected BodyReqGetListDocumentFromCROMType bodyReqGetListDocumentFromCROM;

    /**
     * Gets the value of the bodyReqGetListDocumentFromCROM property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqGetListDocumentFromCROMType }
     *     
     */
    public BodyReqGetListDocumentFromCROMType getBodyReqGetListDocumentFromCROM() {
        return bodyReqGetListDocumentFromCROM;
    }

    /**
     * Sets the value of the bodyReqGetListDocumentFromCROM property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqGetListDocumentFromCROMType }
     *     
     */
    public void setBodyReqGetListDocumentFromCROM(BodyReqGetListDocumentFromCROMType value) {
        this.bodyReqGetListDocumentFromCROM = value;
    }

}
