//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.01 at 11:10:19 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bidv.com/global/vn/apps/ecm/getlistdocumentfromcrom/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soa.apps.ecm.getListDocumentCrom;
