//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 04:29:10 PM ICT 
//


package bidv.soa.sibs.LNAccount.CreateAcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodyReqCreateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BodyReqCreateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseXfer" type="{http://www.bidv.com/global/common/bank/1.0}BaseXferType"/>
 *         &lt;element name="AANo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FacCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FacSeq" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amt">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LoanAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CurrCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MaturityDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FinalMaturityDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntDueDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntDueDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstPmtDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstPmtDt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AcctNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DrawingLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrancheMaxTerm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrancheMaxCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoanTerm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LoanCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OriginationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InterestBase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="YearBase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModeOfInterest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PmtCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntPmtFreq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntPmtFreqCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PmtFreq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PmtFreqCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CapitalPrepaym" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ResidualValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DayB4Rate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DealerCalMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DealerRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CalcRateBaseOn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaturityRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AdvanceMargin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateVariance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateVarianceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateVarianceFloor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateVarianceCeiling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateFloor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateCeiling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InterestRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateReviewDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateReviewDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateReviewTerm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateReviewCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateUserReviewDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateUserReviewCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateUserReviewTerm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RateUserReviewDay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PaymentAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FinalPaymAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsCalculate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodyReqCreateType", namespace = "http://www.bidv.com/entity/vn/loan/lnaccount/createacc/1.0", propOrder = {
    "baseXfer",
    "aaNo",
    "facCode",
    "facSeq",
    "productType",
    "amt",
    "maturityDt",
    "finalMaturityDt",
    "intDueDay",
    "intDueDt",
    "firstPmtDay",
    "firstPmtDt",
    "acctNo",
    "drawingLimit",
    "trancheMaxTerm",
    "trancheMaxCode",
    "loanTerm",
    "loanCode",
    "originationDate",
    "interestBase",
    "yearBase",
    "modeOfInterest",
    "pmtCode",
    "intPmtFreq",
    "intPmtFreqCode",
    "pmtFreq",
    "pmtFreqCode",
    "capitalPrepaym",
    "residualValue",
    "dayB4Rate",
    "dealerCalMethod",
    "dealerRate",
    "calcRateBaseOn",
    "maturityRate",
    "advanceMargin",
    "rateNumber",
    "rateVariance",
    "rateVarianceCode",
    "rateVarianceFloor",
    "rateVarianceCeiling",
    "rateFloor",
    "rateCeiling",
    "interestRate",
    "rateReviewDate",
    "rateReviewDay",
    "rateReviewTerm",
    "rateReviewCode",
    "rateUserReviewDate",
    "rateUserReviewCode",
    "rateUserReviewTerm",
    "rateUserReviewDay",
    "paymentAmount",
    "finalPaymAmt",
    "isCalculate"
})
public class BodyReqCreateType {

    @XmlElement(name = "BaseXfer", required = true)
    protected BaseXferType baseXfer;
    @XmlElement(name = "AANo", required = true)
    protected String aaNo;
    @XmlElement(name = "FacCode", required = true)
    protected String facCode;
    @XmlElement(name = "FacSeq", required = true)
    protected String facSeq;
    @XmlElement(name = "ProductType", required = true)
    protected String productType;
    @XmlElement(name = "Amt", required = true)
    protected BodyReqCreateType.Amt amt;
    @XmlElement(name = "MaturityDt")
    protected String maturityDt;
    @XmlElement(name = "FinalMaturityDt")
    protected String finalMaturityDt;
    @XmlElement(name = "IntDueDay")
    protected String intDueDay;
    @XmlElement(name = "IntDueDt")
    protected String intDueDt;
    @XmlElement(name = "FirstPmtDay")
    protected String firstPmtDay;
    @XmlElement(name = "FirstPmtDt")
    protected String firstPmtDt;
    @XmlElement(name = "AcctNo")
    protected String acctNo;
    @XmlElement(name = "DrawingLimit")
    protected String drawingLimit;
    @XmlElement(name = "TrancheMaxTerm")
    protected String trancheMaxTerm;
    @XmlElement(name = "TrancheMaxCode")
    protected String trancheMaxCode;
    @XmlElement(name = "LoanTerm")
    protected String loanTerm;
    @XmlElement(name = "LoanCode")
    protected String loanCode;
    @XmlElement(name = "OriginationDate")
    protected String originationDate;
    @XmlElement(name = "InterestBase")
    protected String interestBase;
    @XmlElement(name = "YearBase")
    protected String yearBase;
    @XmlElement(name = "ModeOfInterest")
    protected String modeOfInterest;
    @XmlElement(name = "PmtCode")
    protected String pmtCode;
    @XmlElement(name = "IntPmtFreq")
    protected String intPmtFreq;
    @XmlElement(name = "IntPmtFreqCode")
    protected String intPmtFreqCode;
    @XmlElement(name = "PmtFreq")
    protected String pmtFreq;
    @XmlElement(name = "PmtFreqCode")
    protected String pmtFreqCode;
    @XmlElement(name = "CapitalPrepaym")
    protected String capitalPrepaym;
    @XmlElement(name = "ResidualValue")
    protected String residualValue;
    @XmlElement(name = "DayB4Rate")
    protected String dayB4Rate;
    @XmlElement(name = "DealerCalMethod")
    protected String dealerCalMethod;
    @XmlElement(name = "DealerRate")
    protected String dealerRate;
    @XmlElement(name = "CalcRateBaseOn")
    protected String calcRateBaseOn;
    @XmlElement(name = "MaturityRate")
    protected String maturityRate;
    @XmlElement(name = "AdvanceMargin")
    protected String advanceMargin;
    @XmlElement(name = "RateNumber")
    protected String rateNumber;
    @XmlElement(name = "RateVariance")
    protected String rateVariance;
    @XmlElement(name = "RateVarianceCode")
    protected String rateVarianceCode;
    @XmlElement(name = "RateVarianceFloor")
    protected String rateVarianceFloor;
    @XmlElement(name = "RateVarianceCeiling")
    protected String rateVarianceCeiling;
    @XmlElement(name = "RateFloor")
    protected String rateFloor;
    @XmlElement(name = "RateCeiling")
    protected String rateCeiling;
    @XmlElement(name = "InterestRate")
    protected String interestRate;
    @XmlElement(name = "RateReviewDate")
    protected String rateReviewDate;
    @XmlElement(name = "RateReviewDay")
    protected String rateReviewDay;
    @XmlElement(name = "RateReviewTerm")
    protected String rateReviewTerm;
    @XmlElement(name = "RateReviewCode")
    protected String rateReviewCode;
    @XmlElement(name = "RateUserReviewDate")
    protected String rateUserReviewDate;
    @XmlElement(name = "RateUserReviewCode")
    protected String rateUserReviewCode;
    @XmlElement(name = "RateUserReviewTerm")
    protected String rateUserReviewTerm;
    @XmlElement(name = "RateUserReviewDay")
    protected String rateUserReviewDay;
    @XmlElement(name = "PaymentAmount")
    protected String paymentAmount;
    @XmlElement(name = "FinalPaymAmt")
    protected String finalPaymAmt;
    @XmlElement(name = "IsCalculate")
    protected String isCalculate;

    /**
     * Gets the value of the baseXfer property.
     * 
     * @return
     *     possible object is
     *     {@link BaseXferType }
     *     
     */
    public BaseXferType getBaseXfer() {
        return baseXfer;
    }

    /**
     * Sets the value of the baseXfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseXferType }
     *     
     */
    public void setBaseXfer(BaseXferType value) {
        this.baseXfer = value;
    }

    /**
     * Gets the value of the aaNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAANo() {
        return aaNo;
    }

    /**
     * Sets the value of the aaNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAANo(String value) {
        this.aaNo = value;
    }

    /**
     * Gets the value of the facCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacCode() {
        return facCode;
    }

    /**
     * Sets the value of the facCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacCode(String value) {
        this.facCode = value;
    }

    /**
     * Gets the value of the facSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacSeq() {
        return facSeq;
    }

    /**
     * Sets the value of the facSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacSeq(String value) {
        this.facSeq = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqCreateType.Amt }
     *     
     */
    public BodyReqCreateType.Amt getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqCreateType.Amt }
     *     
     */
    public void setAmt(BodyReqCreateType.Amt value) {
        this.amt = value;
    }

    /**
     * Gets the value of the maturityDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityDt() {
        return maturityDt;
    }

    /**
     * Sets the value of the maturityDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityDt(String value) {
        this.maturityDt = value;
    }

    /**
     * Gets the value of the finalMaturityDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalMaturityDt() {
        return finalMaturityDt;
    }

    /**
     * Sets the value of the finalMaturityDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalMaturityDt(String value) {
        this.finalMaturityDt = value;
    }

    /**
     * Gets the value of the intDueDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntDueDay() {
        return intDueDay;
    }

    /**
     * Sets the value of the intDueDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntDueDay(String value) {
        this.intDueDay = value;
    }

    /**
     * Gets the value of the intDueDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntDueDt() {
        return intDueDt;
    }

    /**
     * Sets the value of the intDueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntDueDt(String value) {
        this.intDueDt = value;
    }

    /**
     * Gets the value of the firstPmtDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPmtDay() {
        return firstPmtDay;
    }

    /**
     * Sets the value of the firstPmtDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPmtDay(String value) {
        this.firstPmtDay = value;
    }

    /**
     * Gets the value of the firstPmtDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstPmtDt() {
        return firstPmtDt;
    }

    /**
     * Sets the value of the firstPmtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstPmtDt(String value) {
        this.firstPmtDt = value;
    }

    /**
     * Gets the value of the acctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * Sets the value of the acctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNo(String value) {
        this.acctNo = value;
    }

    /**
     * Gets the value of the drawingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawingLimit() {
        return drawingLimit;
    }

    /**
     * Sets the value of the drawingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawingLimit(String value) {
        this.drawingLimit = value;
    }

    /**
     * Gets the value of the trancheMaxTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrancheMaxTerm() {
        return trancheMaxTerm;
    }

    /**
     * Sets the value of the trancheMaxTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrancheMaxTerm(String value) {
        this.trancheMaxTerm = value;
    }

    /**
     * Gets the value of the trancheMaxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrancheMaxCode() {
        return trancheMaxCode;
    }

    /**
     * Sets the value of the trancheMaxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrancheMaxCode(String value) {
        this.trancheMaxCode = value;
    }

    /**
     * Gets the value of the loanTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanTerm() {
        return loanTerm;
    }

    /**
     * Sets the value of the loanTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanTerm(String value) {
        this.loanTerm = value;
    }

    /**
     * Gets the value of the loanCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanCode() {
        return loanCode;
    }

    /**
     * Sets the value of the loanCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanCode(String value) {
        this.loanCode = value;
    }

    /**
     * Gets the value of the originationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginationDate() {
        return originationDate;
    }

    /**
     * Sets the value of the originationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginationDate(String value) {
        this.originationDate = value;
    }

    /**
     * Gets the value of the interestBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestBase() {
        return interestBase;
    }

    /**
     * Sets the value of the interestBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestBase(String value) {
        this.interestBase = value;
    }

    /**
     * Gets the value of the yearBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearBase() {
        return yearBase;
    }

    /**
     * Sets the value of the yearBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearBase(String value) {
        this.yearBase = value;
    }

    /**
     * Gets the value of the modeOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeOfInterest() {
        return modeOfInterest;
    }

    /**
     * Sets the value of the modeOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeOfInterest(String value) {
        this.modeOfInterest = value;
    }

    /**
     * Gets the value of the pmtCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtCode() {
        return pmtCode;
    }

    /**
     * Sets the value of the pmtCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtCode(String value) {
        this.pmtCode = value;
    }

    /**
     * Gets the value of the intPmtFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntPmtFreq() {
        return intPmtFreq;
    }

    /**
     * Sets the value of the intPmtFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntPmtFreq(String value) {
        this.intPmtFreq = value;
    }

    /**
     * Gets the value of the intPmtFreqCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntPmtFreqCode() {
        return intPmtFreqCode;
    }

    /**
     * Sets the value of the intPmtFreqCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntPmtFreqCode(String value) {
        this.intPmtFreqCode = value;
    }

    /**
     * Gets the value of the pmtFreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtFreq() {
        return pmtFreq;
    }

    /**
     * Sets the value of the pmtFreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtFreq(String value) {
        this.pmtFreq = value;
    }

    /**
     * Gets the value of the pmtFreqCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPmtFreqCode() {
        return pmtFreqCode;
    }

    /**
     * Sets the value of the pmtFreqCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPmtFreqCode(String value) {
        this.pmtFreqCode = value;
    }

    /**
     * Gets the value of the capitalPrepaym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapitalPrepaym() {
        return capitalPrepaym;
    }

    /**
     * Sets the value of the capitalPrepaym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapitalPrepaym(String value) {
        this.capitalPrepaym = value;
    }

    /**
     * Gets the value of the residualValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidualValue() {
        return residualValue;
    }

    /**
     * Sets the value of the residualValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidualValue(String value) {
        this.residualValue = value;
    }

    /**
     * Gets the value of the dayB4Rate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayB4Rate() {
        return dayB4Rate;
    }

    /**
     * Sets the value of the dayB4Rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayB4Rate(String value) {
        this.dayB4Rate = value;
    }

    /**
     * Gets the value of the dealerCalMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerCalMethod() {
        return dealerCalMethod;
    }

    /**
     * Sets the value of the dealerCalMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerCalMethod(String value) {
        this.dealerCalMethod = value;
    }

    /**
     * Gets the value of the dealerRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerRate() {
        return dealerRate;
    }

    /**
     * Sets the value of the dealerRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerRate(String value) {
        this.dealerRate = value;
    }

    /**
     * Gets the value of the calcRateBaseOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalcRateBaseOn() {
        return calcRateBaseOn;
    }

    /**
     * Sets the value of the calcRateBaseOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalcRateBaseOn(String value) {
        this.calcRateBaseOn = value;
    }

    /**
     * Gets the value of the maturityRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityRate() {
        return maturityRate;
    }

    /**
     * Sets the value of the maturityRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityRate(String value) {
        this.maturityRate = value;
    }

    /**
     * Gets the value of the advanceMargin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvanceMargin() {
        return advanceMargin;
    }

    /**
     * Sets the value of the advanceMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvanceMargin(String value) {
        this.advanceMargin = value;
    }

    /**
     * Gets the value of the rateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateNumber() {
        return rateNumber;
    }

    /**
     * Sets the value of the rateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateNumber(String value) {
        this.rateNumber = value;
    }

    /**
     * Gets the value of the rateVariance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateVariance() {
        return rateVariance;
    }

    /**
     * Sets the value of the rateVariance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateVariance(String value) {
        this.rateVariance = value;
    }

    /**
     * Gets the value of the rateVarianceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateVarianceCode() {
        return rateVarianceCode;
    }

    /**
     * Sets the value of the rateVarianceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateVarianceCode(String value) {
        this.rateVarianceCode = value;
    }

    /**
     * Gets the value of the rateVarianceFloor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateVarianceFloor() {
        return rateVarianceFloor;
    }

    /**
     * Sets the value of the rateVarianceFloor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateVarianceFloor(String value) {
        this.rateVarianceFloor = value;
    }

    /**
     * Gets the value of the rateVarianceCeiling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateVarianceCeiling() {
        return rateVarianceCeiling;
    }

    /**
     * Sets the value of the rateVarianceCeiling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateVarianceCeiling(String value) {
        this.rateVarianceCeiling = value;
    }

    /**
     * Gets the value of the rateFloor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateFloor() {
        return rateFloor;
    }

    /**
     * Sets the value of the rateFloor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateFloor(String value) {
        this.rateFloor = value;
    }

    /**
     * Gets the value of the rateCeiling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateCeiling() {
        return rateCeiling;
    }

    /**
     * Sets the value of the rateCeiling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateCeiling(String value) {
        this.rateCeiling = value;
    }

    /**
     * Gets the value of the interestRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestRate() {
        return interestRate;
    }

    /**
     * Sets the value of the interestRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestRate(String value) {
        this.interestRate = value;
    }

    /**
     * Gets the value of the rateReviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateReviewDate() {
        return rateReviewDate;
    }

    /**
     * Sets the value of the rateReviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateReviewDate(String value) {
        this.rateReviewDate = value;
    }

    /**
     * Gets the value of the rateReviewDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateReviewDay() {
        return rateReviewDay;
    }

    /**
     * Sets the value of the rateReviewDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateReviewDay(String value) {
        this.rateReviewDay = value;
    }

    /**
     * Gets the value of the rateReviewTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateReviewTerm() {
        return rateReviewTerm;
    }

    /**
     * Sets the value of the rateReviewTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateReviewTerm(String value) {
        this.rateReviewTerm = value;
    }

    /**
     * Gets the value of the rateReviewCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateReviewCode() {
        return rateReviewCode;
    }

    /**
     * Sets the value of the rateReviewCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateReviewCode(String value) {
        this.rateReviewCode = value;
    }

    /**
     * Gets the value of the rateUserReviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateUserReviewDate() {
        return rateUserReviewDate;
    }

    /**
     * Sets the value of the rateUserReviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateUserReviewDate(String value) {
        this.rateUserReviewDate = value;
    }

    /**
     * Gets the value of the rateUserReviewCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateUserReviewCode() {
        return rateUserReviewCode;
    }

    /**
     * Sets the value of the rateUserReviewCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateUserReviewCode(String value) {
        this.rateUserReviewCode = value;
    }

    /**
     * Gets the value of the rateUserReviewTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateUserReviewTerm() {
        return rateUserReviewTerm;
    }

    /**
     * Sets the value of the rateUserReviewTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateUserReviewTerm(String value) {
        this.rateUserReviewTerm = value;
    }

    /**
     * Gets the value of the rateUserReviewDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRateUserReviewDay() {
        return rateUserReviewDay;
    }

    /**
     * Sets the value of the rateUserReviewDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRateUserReviewDay(String value) {
        this.rateUserReviewDay = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmount(String value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the finalPaymAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalPaymAmt() {
        return finalPaymAmt;
    }

    /**
     * Sets the value of the finalPaymAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalPaymAmt(String value) {
        this.finalPaymAmt = value;
    }

    /**
     * Gets the value of the isCalculate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCalculate() {
        return isCalculate;
    }

    /**
     * Sets the value of the isCalculate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCalculate(String value) {
        this.isCalculate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LoanAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CurrCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "loanAmt",
        "currCode"
    })
    public static class Amt {

        @XmlElement(name = "LoanAmt", namespace = "http://www.bidv.com/entity/vn/loan/lnaccount/createacc/1.0", required = true)
        protected String loanAmt;
        @XmlElement(name = "CurrCode", namespace = "http://www.bidv.com/entity/vn/loan/lnaccount/createacc/1.0", required = true)
        protected String currCode;

        /**
         * Gets the value of the loanAmt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLoanAmt() {
            return loanAmt;
        }

        /**
         * Sets the value of the loanAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLoanAmt(String value) {
            this.loanAmt = value;
        }

        /**
         * Gets the value of the currCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrCode() {
            return currCode;
        }

        /**
         * Sets the value of the currCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrCode(String value) {
            this.currCode = value;
        }

    }

}
