//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 02:47:43 PM ICT 
//


package bidv.soa.sibs.detailEntryHold;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccDetailEntryHoldReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccDetailEntryHoldReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/entity/vn/account/acchold/detailentryhold/1.0}BodyReqDetailEntryHold"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "AccDetailEntryHoldReq", namespace = "http://www.bidv.com/entity/vn/account/acchold/detailentryhold/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccDetailEntryHoldReqType", namespace = "http://www.bidv.com/entity/vn/account/acchold/detailentryhold/1.0", propOrder = {
    "bodyReqDetailEntryHold"
})
public class AccDetailEntryHoldReqType
    extends BaseServiceEnvelopeRequestType
{

    @XmlElement(name = "BodyReqDetailEntryHold", required = true)
    protected BodyReqDetailEntryHoldType bodyReqDetailEntryHold;

    /**
     * Gets the value of the bodyReqDetailEntryHold property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqDetailEntryHoldType }
     *     
     */
    public BodyReqDetailEntryHoldType getBodyReqDetailEntryHold() {
        return bodyReqDetailEntryHold;
    }

    /**
     * Sets the value of the bodyReqDetailEntryHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqDetailEntryHoldType }
     *     
     */
    public void setBodyReqDetailEntryHold(BodyReqDetailEntryHoldType value) {
        this.bodyReqDetailEntryHold = value;
    }

}
