//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.06 at 03:48:53 PM ICT 
//


package bidv.soa.sibs.remittance.GLCashwithdraw.test;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReceiverInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReceiverInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GLAcctNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TTBuyRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DRAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReceiverInfoType", namespace = "http://www.bidv.com/entity/vn/remittance/glcashwithdraw/create/1.0", propOrder = {
    "glAcctNo",
    "curCode",
    "ttBuyRate",
    "drAmount"
})
public class ReceiverInfoType {

    @XmlElement(name = "GLAcctNo")
    protected String glAcctNo;
    @XmlElement(name = "CurCode")
    protected String curCode;
    @XmlElement(name = "TTBuyRate")
    protected String ttBuyRate;
    @XmlElement(name = "DRAmount")
    protected String drAmount;

    /**
     * Gets the value of the glAcctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLAcctNo() {
        return glAcctNo;
    }

    /**
     * Sets the value of the glAcctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLAcctNo(String value) {
        this.glAcctNo = value;
    }

    /**
     * Gets the value of the curCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurCode() {
        return curCode;
    }

    /**
     * Sets the value of the curCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurCode(String value) {
        this.curCode = value;
    }

    /**
     * Gets the value of the ttBuyRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTTBuyRate() {
        return ttBuyRate;
    }

    /**
     * Sets the value of the ttBuyRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTTBuyRate(String value) {
        this.ttBuyRate = value;
    }

    /**
     * Gets the value of the drAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRAmount() {
        return drAmount;
    }

    /**
     * Sets the value of the drAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRAmount(String value) {
        this.drAmount = value;
    }

}
