//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.17 at 09:22:32 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bidv.com/global/vn/apps/ecm/approvedocument/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package soa.apps.ecm.approvalDocument;
