//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.22 at 06:23:02 PM ICT 
//


package bidv.soa.ach247.inquiry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ACHInquiryReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACHInquiryReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/entity/vn/apps/ach/inquiry/1.0}BodyReqACHInquiry"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "ACHInquiryReq", namespace = "http://www.bidv.com/entity/vn/apps/ach/tranfer/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACHInquiryReqType", namespace = "http://www.bidv.com/entity/vn/apps/ach/inquiry/1.0", propOrder = {
    "bodyReqACHInquiry"
})
public class ACHInquiryReqType
    extends BaseServiceEnvelopeRequestType
{

    @XmlElement(name = "BodyReqACHInquiry", required = true)
    protected BodyReqACHInquiryType bodyReqACHInquiry;

    /**
     * Gets the value of the bodyReqACHInquiry property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqACHInquiryType }
     *     
     */
    public BodyReqACHInquiryType getBodyReqACHInquiry() {
        return bodyReqACHInquiry;
    }

    /**
     * Sets the value of the bodyReqACHInquiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqACHInquiryType }
     *     
     */
    public void setBodyReqACHInquiry(BodyReqACHInquiryType value) {
        this.bodyReqACHInquiry = value;
    }

}
