//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 05:02:00 PM ICT 
//


package bidv.soa.sibs.LNAccount.MasterAANoInq;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodyReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BodyReqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseXfer" type="{http://www.bidv.com/global/common/bank/1.0}BaseXferType"/>
 *         &lt;element name="CIF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AANo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ACFNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Fac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Seq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AcctNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MoreRecords" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rownum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodyReqType", namespace = "http://www.bidv.com/entity/vn/loan/lnaccount/masteraanoinq/1.0", propOrder = {
    "baseXfer",
    "cif",
    "aaNo",
    "acfNo",
    "fac",
    "seq",
    "acctNo",
    "type",
    "moreRecords",
    "rownum"
})
public class BodyReqType {

    @XmlElement(name = "BaseXfer", required = true)
    protected BaseXferType baseXfer;
    @XmlElement(name = "CIF")
    protected String cif;
    @XmlElement(name = "AANo")
    protected String aaNo;
    @XmlElement(name = "ACFNo")
    protected String acfNo;
    @XmlElement(name = "Fac")
    protected String fac;
    @XmlElement(name = "Seq")
    protected String seq;
    @XmlElement(name = "AcctNo")
    protected String acctNo;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "MoreRecords")
    protected String moreRecords;
    @XmlElement(name = "Rownum")
    protected String rownum;

    /**
     * Gets the value of the baseXfer property.
     * 
     * @return
     *     possible object is
     *     {@link BaseXferType }
     *     
     */
    public BaseXferType getBaseXfer() {
        return baseXfer;
    }

    /**
     * Sets the value of the baseXfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseXferType }
     *     
     */
    public void setBaseXfer(BaseXferType value) {
        this.baseXfer = value;
    }

    /**
     * Gets the value of the cif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIF() {
        return cif;
    }

    /**
     * Sets the value of the cif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIF(String value) {
        this.cif = value;
    }

    /**
     * Gets the value of the aaNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAANo() {
        return aaNo;
    }

    /**
     * Sets the value of the aaNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAANo(String value) {
        this.aaNo = value;
    }

    /**
     * Gets the value of the acfNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACFNo() {
        return acfNo;
    }

    /**
     * Sets the value of the acfNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACFNo(String value) {
        this.acfNo = value;
    }

    /**
     * Gets the value of the fac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFac() {
        return fac;
    }

    /**
     * Sets the value of the fac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFac(String value) {
        this.fac = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeq(String value) {
        this.seq = value;
    }

    /**
     * Gets the value of the acctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * Sets the value of the acctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNo(String value) {
        this.acctNo = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the moreRecords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoreRecords() {
        return moreRecords;
    }

    /**
     * Sets the value of the moreRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoreRecords(String value) {
        this.moreRecords = value;
    }

    /**
     * Gets the value of the rownum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRownum() {
        return rownum;
    }

    /**
     * Sets the value of the rownum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRownum(String value) {
        this.rownum = value;
    }

}
