//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 05:30:50 PM ICT 
//


package bidv.soa.sibs.BIDVCash.VaultInquiry;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BodyResInquiryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BodyResInquiryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/entity/vn/bidvcash/vaultinquiry/1.0}CashDeno" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BodyResInquiryType", namespace = "http://www.bidv.com/entity/vn/bidvcash/vaultinquiry/1.0", propOrder = {
    "cashDeno"
})
public class BodyResInquiryType {

    @XmlElement(name = "CashDeno")
    protected List<CashDeno> cashDeno;

    /**
     * Gets the value of the cashDeno property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashDeno property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashDeno().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashDeno }
     * 
     * 
     */
    public List<CashDeno> getCashDeno() {
        if (cashDeno == null) {
            cashDeno = new ArrayList<CashDeno>();
        }
        return this.cashDeno;
    }

}
