//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 11:47:14 AM ICT 
//


package bidv.soa.sibs.acctChangeHold;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeHoldReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangeHoldReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/global/vn/account/accthold/changehold/1.0}BodyReqChangeHold"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "ChangeHoldReq", namespace = "http://www.bidv.com/global/vn/account/accthold/changehold/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangeHoldReqType", namespace = "http://www.bidv.com/global/vn/account/accthold/changehold/1.0", propOrder = {
    "bodyReqChangeHold"
})
public class ChangeHoldReqType
    extends BaseServiceEnvelopeRequestType
{

    @XmlElement(name = "BodyReqChangeHold", required = true)
    protected BodyReqChangeHoldType bodyReqChangeHold;

    /**
     * Gets the value of the bodyReqChangeHold property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqChangeHoldType }
     *     
     */
    public BodyReqChangeHoldType getBodyReqChangeHold() {
        return bodyReqChangeHold;
    }

    /**
     * Sets the value of the bodyReqChangeHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqChangeHoldType }
     *     
     */
    public void setBodyReqChangeHold(BodyReqChangeHoldType value) {
        this.bodyReqChangeHold = value;
    }

}
