//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 04:49:21 PM ICT 
//


package bidv.soa.sibs.LNAccount.LNAccountDeleteAcc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LNAccountResType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LNAccountResType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeResponseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/entity/vn/loan/lnaccount/deleteacc/1.0}BodyResDelete"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "LNAccountRes", namespace = "http://www.bidv.com/entity/vn/loan/lnaccount/deleteacc/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LNAccountResType", namespace = "http://www.bidv.com/entity/vn/loan/lnaccount/deleteacc/1.0", propOrder = {
    "bodyResDelete"
})
public class LNAccountResType
    extends BaseServiceEnvelopeResponseType
{

    @XmlElement(name = "BodyResDelete", required = true)
    protected BodyResDeleteType bodyResDelete;

    /**
     * Gets the value of the bodyResDelete property.
     * 
     * @return
     *     possible object is
     *     {@link BodyResDeleteType }
     *     
     */
    public BodyResDeleteType getBodyResDelete() {
        return bodyResDelete;
    }

    /**
     * Sets the value of the bodyResDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyResDeleteType }
     *     
     */
    public void setBodyResDelete(BodyResDeleteType value) {
        this.bodyResDelete = value;
    }

}
