//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.07 at 10:36:55 AM ICT 
//


package bidv.soa.sibs.acctDetail.masterInq;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MasterInqResType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MasterInqResType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeResponseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com.vn/entity/global/vn/account/acctdetail/masterinq/1.0}BodyResMasterInquiry"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MasterInqResType", namespace = "http://www.bidv.com.vn/entity/global/vn/account/acctdetail/masterinq/1.0", propOrder = {
    "bodyResMasterInquiry"
})
public class MasterInqResType
    extends BaseServiceEnvelopeResponseType
{

    @XmlElement(name = "BodyResMasterInquiry", required = true)
    protected BodyResMasterInquiryType bodyResMasterInquiry;

    /**
     * Gets the value of the bodyResMasterInquiry property.
     * 
     * @return
     *     possible object is
     *     {@link BodyResMasterInquiryType }
     *     
     */
    public BodyResMasterInquiryType getBodyResMasterInquiry() {
        return bodyResMasterInquiry;
    }

    /**
     * Sets the value of the bodyResMasterInquiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyResMasterInquiryType }
     *     
     */
    public void setBodyResMasterInquiry(BodyResMasterInquiryType value) {
        this.bodyResMasterInquiry = value;
    }

}
