//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.08 at 09:59:47 AM ICT 
//


package bidv.soa.sibs.acctHold;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctHoldReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctHoldReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.bidv.com/common/envelope/serviceenvelope/1.0}BaseServiceEnvelopeRequestType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.bidv.com/global/vn/account/accthold/hold/1.0}BodyReqAcctHold"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "AcctHoldReq", namespace = "http://www.bidv.com/global/vn/account/accthold/hold/1.0")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctHoldReqType", namespace = "http://www.bidv.com/global/vn/account/accthold/hold/1.0", propOrder = {
    "bodyReqAcctHold"
})
public class AcctHoldReqType
    extends BaseServiceEnvelopeRequestType
{

    @XmlElement(name = "BodyReqAcctHold", required = true)
    protected BodyReqAcctHoldType bodyReqAcctHold;

    /**
     * Gets the value of the bodyReqAcctHold property.
     * 
     * @return
     *     possible object is
     *     {@link BodyReqAcctHoldType }
     *     
     */
    public BodyReqAcctHoldType getBodyReqAcctHold() {
        return bodyReqAcctHold;
    }

    /**
     * Sets the value of the bodyReqAcctHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link BodyReqAcctHoldType }
     *     
     */
    public void setBodyReqAcctHold(BodyReqAcctHoldType value) {
        this.bodyReqAcctHold = value;
    }

}
